import 'dart:async';
import 'package:cobrador/domain/recurring_appointment.dart';
import 'package:cobrador/presentation/providers/firebase_providers.dart';
import 'package:cobrador/presentation/providers/ledger_provider.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'create_recurring_appointment_controller.g.dart';

@riverpod
class CreateRecurringAppointmentController
    extends _$CreateRecurringAppointmentController {
  @override
  FutureOr<void> build() {}

  Future<void> submit({
    required String patientId,
    required String concept,
    required double amount,
    required Frequency frequency,
    required DateTime baseDate,
    DateTime? endDate,
  }) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final auth = ref.read(firebaseAuthProvider);
      final providerId = auth.currentUser?.uid;

      if (providerId == null) {
        throw Exception('Usuario no autenticado');
      }

      final newRecurring = RecurringAppointment(
        id: '', // Auto-generated by repo
        patientId: patientId,
        providerId: providerId,
        concept: concept,
        defaultAmount: amount,
        frequency: frequency,
        baseDate: baseDate,
        endDate: endDate,
      );

      await ref
          .read(
            ledgerProvider(
              providerId: providerId,
              patientId: patientId,
            ).notifier,
          )
          .createRecurringAppointment(newRecurring);
    });
  }
}
