import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:cobrador/data/repositories/ledger_repository_impl.dart';
import 'package:cobrador/domain/appointment.dart';
import 'package:cobrador/domain/payment.dart';
import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

class MockFirebaseFunctions extends Mock implements FirebaseFunctions {}

class MockHttpsCallable extends Mock implements HttpsCallable {}

class MockHttpsCallableResult extends Mock
    implements HttpsCallableResult<dynamic> {}

void main() {
  late LedgerRepositoryImpl repository;
  late FakeFirebaseFirestore fakeFirestore;
  late MockFirebaseFunctions mockFunctions;

  setUp(() {
    fakeFirestore = FakeFirebaseFirestore();
    mockFunctions = MockFirebaseFunctions();
    repository = LedgerRepositoryImpl(fakeFirestore, mockFunctions);
  });

  // Helper: returns the appointments subcollection reference for the new path
  CollectionReference<Map<String, dynamic>> appointmentsRef(
    String providerId,
    String patientId,
  ) {
    return fakeFirestore
        .collection('providers')
        .doc(providerId)
        .collection('patients')
        .doc(patientId)
        .collection('appointments');
  }

  // Helper: returns the payments subcollection reference for the new path
  CollectionReference<Map<String, dynamic>> paymentsRef(
    String providerId,
    String patientId,
  ) {
    return fakeFirestore
        .collection('providers')
        .doc(providerId)
        .collection('patients')
        .doc(patientId)
        .collection('payments');
  }

  // ─── createAppointment ─────────────────────────────────────

  group('createAppointment', () {
    final tAppointment = Appointment(
      id: '',
      patientId: 'pat1',
      providerId: 'prov1',
      date: DateTime(2026, 1, 15),
      concept: 'Odontologia',
      totalAmount: 50.0,
      amountPaid: 0.0,
      status: AppointmentStatus.unpaid,
    );

    test(
      'should return created entity with auto-generated ID when successful',
      () async {
        final result = await repository.createAppointment(tAppointment);

        expect(result.isRight(), true);
        result.map((appointment) {
          expect(appointment.id, isNotEmpty);
          expect(appointment.concept, 'Odontologia');
          expect(appointment.totalAmount, 50.0);
          expect(appointment.patientId, 'pat1');
          expect(appointment.providerId, 'prov1');
        });

        // Verify correct subcollection path
        final snapshot = await appointmentsRef('prov1', 'pat1').get();
        expect(snapshot.docs.length, 1);
        expect(snapshot.docs.first.data()['concept'], 'Odontologia');
      },
    );

    test('should persist the correct fields in Firestore document', () async {
      await repository.createAppointment(tAppointment);

      final snapshot = await appointmentsRef('prov1', 'pat1').get();
      final data = snapshot.docs.first.data();

      expect(data['patientId'], 'pat1');
      expect(data['providerId'], 'prov1');
      expect(data['concept'], 'Odontologia');
      expect(data['totalAmount'], 50.0);
      expect(data['amountPaid'], 0.0);
      expect(data['status'], 'unpaid');
    });
  });

  // ─── registerPayment ───────────────────────────────────────

  group('registerPayment', () {
    final tPayment = Payment(
      id: '',
      patientId: 'pat1',
      providerId: 'prov1',
      amount: 150.0,
      date: DateTime(2026, 2, 10),
    );

    test('should return Payment with ID generated by Cloud Function', () async {
      final mockCallable = MockHttpsCallable();
      final mockResult = MockHttpsCallableResult();

      when(
        () => mockFunctions.httpsCallable('payments-registerPayment'),
      ).thenReturn(mockCallable);

      when(() => mockCallable.call(any())).thenAnswer((_) async => mockResult);
      when(
        () => mockResult.data,
      ).thenReturn(<String, dynamic>{'paymentId': 'func_gen_123'});

      final result = await repository.registerPayment(tPayment);

      expect(result.isRight(), true);
      result.map((payment) {
        expect(payment.id, 'func_gen_123');
        expect(payment.amount, 150.0);
        expect(payment.patientId, 'pat1');
      });

      verify(
        () => mockFunctions.httpsCallable('payments-registerPayment'),
      ).called(1);
    });
  });

  // ─── deleteAppointment ─────────────────────────────────────

  group('deleteAppointment', () {
    test('should successfully delete the appointment document', () async {
      final docRef = await appointmentsRef('prov1', 'pat1').add({
        'patientId': 'pat1',
        'providerId': 'prov1',
        'concept': 'Consulta',
        'totalAmount': 50.0,
        'amountPaid': 0.0,
        'status': 'unpaid',
        'date': Timestamp.fromDate(DateTime(2026, 1, 15)),
      });

      final result = await repository.deleteAppointment(
        'prov1',
        'pat1',
        docRef.id,
      );

      expect(result.isRight(), true);

      final snapshot =
          await appointmentsRef('prov1', 'pat1').doc(docRef.id).get();
      expect(snapshot.exists, false);
    });
  });

  // ─── deletePayment ─────────────────────────────────────────

  group('deletePayment', () {
    test('should successfully delete the payment document', () async {
      final docRef = await paymentsRef('prov1', 'pat1').add({
        'patientId': 'pat1',
        'providerId': 'prov1',
        'amount': 100.0,
        'date': Timestamp.fromDate(DateTime(2026, 1, 15)),
      });

      final result = await repository.deletePayment('prov1', 'pat1', docRef.id);

      expect(result.isRight(), true);

      final snapshot = await paymentsRef('prov1', 'pat1').doc(docRef.id).get();
      expect(snapshot.exists, false);
    });
  });

  // ─── watchAppointments ─────────────────────────────────────

  group('watchAppointments', () {
    test('should emit empty list when no appointments exist', () async {
      final stream = repository.watchAppointments(
        providerId: 'prov1',
        patientId: 'pat1',
      );

      await expectLater(stream, emits(isEmpty));
    });

    test(
      'should only return appointments for the given patient and provider',
      () async {
        await appointmentsRef('prov1', 'pat1').add({
          'patientId': 'pat1',
          'providerId': 'prov1',
          'concept': 'Consulta A',
          'totalAmount': 100.0,
          'amountPaid': 0.0,
          'status': 'unpaid',
          'date': Timestamp.fromDate(DateTime(2026, 1, 1)),
        });
        // A different patient under the same provider — should NOT be returned
        await appointmentsRef('prov1', 'pat_other').add({
          'patientId': 'pat_other',
          'providerId': 'prov1',
          'concept': 'Consulta B',
          'totalAmount': 200.0,
          'amountPaid': 0.0,
          'status': 'unpaid',
          'date': Timestamp.fromDate(DateTime(2026, 1, 2)),
        });

        final stream = repository.watchAppointments(
          providerId: 'prov1',
          patientId: 'pat1',
        );
        final appointments = await stream.first;

        expect(appointments.length, 1);
        expect(appointments.first.concept, 'Consulta A');
      },
    );
  });

  // ─── getPaymentsPage ───────────────────────────────────────

  group('getPaymentsPage', () {
    test('should return empty list when no payments exist', () async {
      final result = await repository.getPaymentsPage(
        providerId: 'prov1',
        patientId: 'pat1',
        limit: 8,
      );

      expect(result.isRight(), true);
      result.map((data) {
        expect(data.items, isEmpty);
        expect(data.cursor, isNull);
      });
    });

    test(
      'should only return payments for the given patient and provider',
      () async {
        await paymentsRef('prov1', 'pat1').add({
          'patientId': 'pat1',
          'providerId': 'prov1',
          'amount': 50.0,
          'date': Timestamp.fromDate(DateTime(2026, 1, 5)),
        });
        await paymentsRef('prov1', 'pat_other').add({
          'patientId': 'pat_other',
          'providerId': 'prov1',
          'amount': 75.0,
          'date': Timestamp.fromDate(DateTime(2026, 1, 6)),
        });

        final result = await repository.getPaymentsPage(
          providerId: 'prov1',
          patientId: 'pat1',
          limit: 8,
        );

        expect(result.isRight(), true);
        result.map((data) {
          expect(data.items.length, 1);
          expect(data.items.first.amount, 50.0);
        });
      },
    );
  });

  // ─── NEGATIVE PATHS: Malformed Data ────────────────────────

  group('watchAppointments - malformed data', () {
    test('should error on documents with missing required fields', () async {
      await appointmentsRef('prov1', 'pat1').add({
        'patientId': 'pat1',
        'providerId': 'prov1',
        // Missing: concept, totalAmount, amountPaid, status, date
      });

      final stream = repository.watchAppointments(
        providerId: 'prov1',
        patientId: 'pat1',
      );

      await expectLater(stream, emitsError(isA<TypeError>()));
    });
  });

  group('getPaymentsPage - malformed data', () {
    test(
      'should return Left(Failure) on documents with missing required fields',
      () async {
        await paymentsRef('prov1', 'pat1').add({
          'patientId': 'pat1',
          'providerId': 'prov1',
          // Missing: amount, date
        });

        final result = await repository.getPaymentsPage(
          providerId: 'prov1',
          patientId: 'pat1',
        );

        expect(result.isLeft(), true);
      },
    );
  });
}
