// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArm1SgBKvok52v_1lFRcPfKYkqcUD4cAk',
    appId: '1:968150642290:web:e4c0f1c860a236d7155ceb',
    messagingSenderId: '968150642290',
    projectId: 'quiz-hoot-7ymbj0',
    authDomain: 'quiz-hoot-7ymbj0.firebaseapp.com',
    storageBucket: 'quiz-hoot-7ymbj0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jLGKuz4NZxSf_kxM0egmKqCgC7orl1A',
    appId: '1:968150642290:android:f05759e4c9ff90e6155ceb',
    messagingSenderId: '968150642290',
    projectId: 'quiz-hoot-7ymbj0',
    storageBucket: 'quiz-hoot-7ymbj0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCssSFbgWzN4y1YKLZvLAEpaneBpOI0fk',
    appId: '1:968150642290:ios:856bd5cdcfe7daae155ceb',
    messagingSenderId: '968150642290',
    projectId: 'quiz-hoot-7ymbj0',
    storageBucket: 'quiz-hoot-7ymbj0.firebasestorage.app',
    androidClientId: '968150642290-v586776sl2trlp0uvvottecc09qlft1o.apps.googleusercontent.com',
    iosClientId: '968150642290-qapcsav3t0v692163i4v0chlme6q5764.apps.googleusercontent.com',
    iosBundleId: 'com.provider.cobrador',
  );

}