import 'package:cobrador/domain/patient.dart';
import 'package:cobrador/presentation/providers/firebase_providers.dart';
import 'package:cobrador/presentation/providers/patient_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class CreatePatientSheet extends ConsumerStatefulWidget {
  const CreatePatientSheet({super.key});

  @override
  ConsumerState<CreatePatientSheet> createState() => _CreatePatientSheetState();
}

class _CreatePatientSheetState extends ConsumerState<CreatePatientSheet> {
  final _formKey = GlobalKey<FormState>();
  String _name = '';
  String _phone = '';
  bool _isSubmitting = false;

  Future<void> _submit() async {
    if (_isSubmitting) return;

    if (_formKey.currentState!.validate()) {
      setState(() => _isSubmitting = true);
      _formKey.currentState!.save();

      try {
        final auth = ref.read(firebaseAuthProvider);
        final providerId = auth.currentUser?.uid;
        if (providerId == null) throw Exception('No user logged in');

        final newPatient = Patient(
          id: '', // Auto-generated by backend/Firestore
          providerId: providerId,
          name: _name,
          phoneNumber: _phone,
          createdAt: DateTime.now(),
        );

        await ref
            .read(patientsProvider(providerId).notifier)
            .addPatient(newPatient);

        if (mounted) {
          Navigator.pop(context);
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Paciente guardado exitosamente')),
          );
        }
      } catch (e) {
        if (mounted) {
          setState(() => _isSubmitting = false);
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error: ${e.toString()}')));
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final insets = MediaQuery.viewInsetsOf(context);
    final textTheme = Theme.of(context).textTheme;

    return Padding(
      padding: EdgeInsets.only(
        bottom: insets.bottom + 16,
        left: 24,
        right: 24,
        top: 24,
      ),
      child: Form(
        key: _formKey,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text('Nuevo Paciente', style: textTheme.titleLarge),
            const SizedBox(height: 16),
            TextFormField(
              decoration: const InputDecoration(
                labelText: 'Nombre completo',
                prefixIcon: Icon(Icons.person_outline_rounded),
              ),
              textInputAction: TextInputAction.next,
              validator: (v) => v == null || v.isEmpty ? 'Requerido' : null,
              onSaved: (v) => _name = v ?? '',
            ),
            const SizedBox(height: 16),
            TextFormField(
              decoration: const InputDecoration(
                labelText: 'Teléfono (WhatsApp)',
                prefixIcon: Icon(Icons.phone_outlined),
                hintText: '+54 9 11 1234-5678',
              ),
              keyboardType: TextInputType.phone,
              textInputAction: TextInputAction.done,
              onFieldSubmitted: (_) => _submit(),
              validator: (v) => v == null || v.isEmpty ? 'Requerido' : null,
              onSaved: (v) => _phone = v ?? '',
            ),
            const SizedBox(height: 24),
            FilledButton(
              onPressed: _isSubmitting ? null : _submit,
              child:
                  _isSubmitting
                      ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                      : const Text('Guardar Paciente'),
            ),
          ],
        ),
      ),
    );
  }
}
